
import type { Candidate, Booking, Timesheet } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Eleanor Vance',
    role: 'History Teacher',
    rate: 50,
    rateType: 'hourly',
    rating: 4.9,
    reviews: 24,
    location: 'London, UK',
    qualifications: ['PhD in History', 'QTS'],
    availability: ['2024-08-19', '2024-08-20', '2024-08-21', '2025-01-20', '2025-01-21'],
    imageUrl: 'https://placehold.co/100x100.png',
    cvUrl: '#',
    bio: 'Passionate historian with a knack for making the past come alive for students of all ages.',
  },
  {
    id: '2',
    name: 'Marcus Thorne',
    role: 'Math Teacher',
    rate: 450,
    rateType: 'daily',
    rating: 4.8,
    reviews: 18,
    location: 'Manchester, UK',
    qualifications: ['M.Sc. in Mathematics', '5+ Years Experience', 'PGCE'],
    availability: ['2024-08-22', '2024-08-23'],
    imageUrl: 'https://placehold.co/100x100.png',
    cvUrl: '#',
    bio: 'An experienced math educator who excels at breaking down complex concepts into understandable lessons.',
  },
  {
    id: '3',
    name: 'Isabella Rossi',
    role: 'Teaching Assistant',
    rate: 25,
    rateType: 'hourly',
    rating: 5.0,
    reviews: 32,
    location: 'Birmingham, UK',
    qualifications: ['Child Development Cert.', 'First Aid'],
    availability: ['2024-08-19', '2024-08-26', '2024-08-27'],
    imageUrl: 'https://placehold.co/100x100.png',
    cvUrl: '#',
    bio: 'A nurturing and patient teaching assistant dedicated to creating a supportive and positive learning environment.',
  },
    {
    id: '4',
    name: 'James Peterson',
    role: 'Science Teacher',
    rate: 55,
    rateType: 'hourly',
    rating: 4.7,
    reviews: 21,
    location: 'London, UK',
    qualifications: ['M.Ed', 'Chemistry Specialization', 'QTS'],
    availability: ['2024-08-20', '2024-08-21', '2024-08-28'],
    imageUrl: 'https://placehold.co/100x100.png',
    cvUrl: '#',
    bio: 'Engaging science teacher who loves sparking curiosity through hands-on experiments and real-world examples.',
  },
  {
    id: '5',
    name: 'Priya Sharma',
    role: 'English Teacher',
    rate: 500,
    rateType: 'daily',
    rating: 4.9,
    reviews: 28,
    location: 'Bristol, UK',
    qualifications: ['MA in English Lit', 'TEFL Certified', 'PGCE'],
    availability: ['2024-08-22', '2024-08-23', '2024-08-29', '2024-08-30'],
    imageUrl: 'https://placehold.co/100x100.png',
    cvUrl: '#',
    bio: 'A literature enthusiast committed to developing strong reading and writing skills in her students.',
  },
];

export const mockClientBookings: Booking[] = [
  { id: 'b1', candidateName: 'Eleanor Vance', candidateRole: 'History Teacher', date: '2024-07-15', status: 'Completed' },
  { id: 'b2', candidateName: 'Marcus Thorne', candidateRole: 'Math Teacher', date: '2024-07-18', status: 'Completed' },
  { id: 'b3', candidateName: 'Isabella Rossi', candidateRole: 'Teaching Assistant', date: '2024-08-26', status: 'Confirmed' },
  { id: 'b5', candidateName: 'James Peterson', candidateRole: 'Science Teacher', date: '2024-08-28', status: 'Interview' },
  { id: 'b6', candidateName: 'Priya Sharma', candidateRole: 'English Teacher', date: '2024-07-22', status: 'Completed' },
  { id: 'b7', candidateName: 'Eleanor Vance', candidateRole: 'History Teacher', date: '2024-08-12', status: 'Confirmed' },
  { id: 'b8', candidateName: 'Marcus Thorne', candidateRole: 'Math Teacher', date: '2024-08-15', status: 'Confirmed' },
  { id: 'b9', candidateName: 'Priya Sharma', candidateRole: 'English Teacher', date: '2024-08-21', status: 'Interview' },
  { id: 'b10', candidateName: 'Isabella Rossi', candidateRole: 'Teaching Assistant', date: '2024-08-05', status: 'Completed' },
  { id: 'b11', candidateName: 'James Peterson', candidateRole: 'Science Teacher', date: '2024-08-01', status: 'Completed' },
  { id: 'b12', candidateName: 'Eleanor Vance', candidateRole: 'History Teacher', date: '2024-09-02', status: 'Confirmed' },
  { id: 'b13', candidateName: 'Priya Sharma', candidateRole: 'English Teacher', date: '2024-09-05', status: 'Interview' },
  { id: 'b14', candidateName: 'Marcus Thorne', candidateRole: 'Math Teacher', date: '2024-09-09', status: 'Confirmed' },
  { id: 'b15', candidateName: 'Isabella Rossi', candidateRole: 'Teaching Assistant', date: '2024-07-29', status: 'Completed' },
  // 2025 Data
  { id: 'b16', candidateName: 'Eleanor Vance', candidateRole: 'History Teacher', date: '2025-01-20', status: 'Confirmed' },
  { id: 'b17', candidateName: 'James Peterson', candidateRole: 'Science Teacher', date: '2025-01-22', status: 'Interview' },
  { id: 'b18', candidateName: 'Marcus Thorne', candidateRole: 'Math Teacher', date: '2025-02-10', status: 'Confirmed' },
  { id: 'b19', candidateName: 'Priya Sharma', candidateRole: 'English Teacher', date: '2025-02-14', status: 'Completed' },
];

export const mockCandidateBookings: Booking[] = [
  { id: 'b3', candidateName: 'Isabella Rossi', candidateRole: 'Teaching Assistant', date: '2024-08-26', status: 'Confirmed' },
  { id: 'b4', candidateName: 'Isabella Rossi', candidateRole: 'Teaching Assistant', date: '2024-07-20', status: 'Completed' },
];

export const mockTimesheets: Timesheet[] = [
    {id: 't1', bookingId: 'b4', candidateName: 'Isabella Rossi', date: '2024-07-20', hours: 8, status: 'Approved' },
    {id: 't2', bookingId: 'b-new', candidateName: 'Isabella Rossi', date: '2024-08-19', hours: 6, status: 'Submitted' },
]
