
'use client';
import {
    Briefcase,
    Calendar,
    FileText,
    Home,
    LogOut,
    PenSquare,
    School,
    Search,
    User,
    Users,
    Star,
    MapPin,
    BookUser,
    Calendar as CalendarIcon,
    DollarSign,
    PoundSterling,
    FileText as FileTextIcon,
    CheckCircle,
    ListFilter,
    UserCheck,
    CalendarCheck2,
    Clipboard,
    Sparkles,
    Upload,
    ChevronLeft,
    ChevronRight,
    ClipboardEdit,
    FilePlus2,
    Loader2,
    ListChecks,
    AlertCircle,
    FileClock,
    Lock
} from 'lucide-react';
export {
    Briefcase,
    Calendar,
    FileText,
    Home,
    LogOut,
    PenSquare,
    School,
    Search,
    User,
    Users,
    Star,
    MapPin,
    BookUser,
    CalendarIcon,
    DollarSign,
    PoundSterling,
    FileTextIcon,
    CheckCircle,
    ListFilter,
    UserCheck,
    CalendarCheck2,
    Clipboard,
    Sparkles,
    Upload,
    ChevronLeft,
    ChevronRight,
    ClipboardEdit,
    FilePlus2,
    Loader2,
    ListChecks,
    AlertCircle,
    FileClock,
    Lock
};
